---
- name: Install required packages
  apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

- name: Add public mongo gpg key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc"
    state: present
    validate_certs: no

- name: Add repo to apt sources list
  template:
    src: mongodb-org.list
    dest: "/etc/apt/sources.list.d/mongodb-org-{{mongodb_version}}.list"
    owner: root
    group: root
    mode: 0644

- name: Install mongo packages
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Copy mongod.conf template
  template:
    src: mongod.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Restart mongo service
  service:
    name: mongod
    enabled: yes
    state: restarted

