---
- name: Add public mongo gpg key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3F75C80EE56C41F4E49515B62ACD4032058F8B6B
    state: present

- name: Add repo to apt sources list
  copy:
    src: mongodb-org-3.4.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: 0644

- name: Install mongo packages
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
    force: yes

- name: Copy mongod.conf template
  template:
    src: mongod.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Restart mongo service
  service:
    name: mongod
    enabled: yes
    state: restarted

