---
#- name: Add public mongo gpg key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 3F75C80EE56C41F4E49515B62ACD4032058F8B6B
#    state: present

- name: Add public mongo gpg key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
    validate_certs: no

- name: Add repo to apt sources list
  copy:
    src: mongodb-org-4.2.list
    dest: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: 0644

- name: Install mongo packages
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Copy mongod.conf template
  template:
    src: mongod.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Restart mongo service
  service:
    name: mongod
    enabled: yes
    state: restarted

